name: Python CI

# Trigger the workflow on any push to the main branch or PRs
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      -main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # step1: check out the code from the repo
      - name: check out code
        uses: actions/checkout@v2
        

      # step2: setup the python env
      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

        # step3: install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
        # step4: run tests
      - name: Run tests
        run: pytest
